name: ad-rnaseq-analysis
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.11
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - scikit-learn
  - pip
  - pip:
      - pydeseq2
      - gseapy